IPData API CLI draft
ipdata/python pull request #4
Opened 2020-10-30 16:00 UTC by stasdavydov

2020-10-30 20:27 UTC, jonathan-kosgei requested changes
Let's rename the "--api_key" param to "--api-key"

2020-10-30 20:31 UTC, jonathan-kosgei requested changes
Let's show a cleaner message without the traceback when a user calls any of the commands before setting up an API key eg.

```
ipdata info
Please specify IPData API Key
Traceback (most recent call last):
  File "/home/jonathan/.local/bin/ipdata", line 8, in <module>
    sys.exit(cli())
  File "/home/jonathan/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jonathan/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jonathan/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jonathan/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jonathan/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jonathan/.local/lib/python3.6/site-packages/ipdata/cli.py", line 140, in info
    res = IPData(get_and_check_api_key(api_key)).lookup('8.8.8.8')
  File "/home/jonathan/.local/lib/python3.6/site-packages/ipdata/cli.py", line 50, in get_and_check_api_key
    raise WrongAPIKey
ipdata.cli.WrongAPIKey
```

2020-10-30 20:34 UTC, jonathan-kosgei commented
Seems to be a bug here

```
ipdata init test
Please specify IPData API Key
New API Key is saved to /home/jonathan/.ipdata
```

It asks to specify the key when I have already done so.

2020-10-30 20:36 UTC, jonathan-kosgei commented
There seems to be a bug when getting the users ip address;

```
ipdata myip
Error: IP address 192.168.43.207 is a private IP Address
```
The IP should be retrieved by making a call to `https://api.ipdata.co/ip`

2020-10-30 20:38 UTC, jonathan-kosgei commented
For `ipdata ip 1.1.1.1` is it possible to drop the `ip` sub-command so that users can just do `ipdata 1.1.1.1` to get the information for that IP?

2020-10-30 20:40 UTC, jonathan-kosgei commented
Instead of pretty-printing the response we should just output the json as is so that users can pipe it to `jq` or run other bash commands on the response.

2020-10-30 20:43 UTC, jonathan-kosgei commented
Let's change the `myip` command to `me` and if possible running the `ipdata` command with no parameters should print the user's location information.

2020-10-30 21:21 UTC, stasdavydov commented
> There seems to be a bug when getting the users ip address;
> 
> ```
> ipdata myip
> Error: IP address 192.168.43.207 is a private IP Address
> ```
> 
> The IP should be retrieved by making a call to `https://api.ipdata.co/ip`

Should I add related method to IPData class?

2020-10-30 21:27 UTC, jonathan-kosgei commented
The functionality is already available;

```
from ipdata import ipdata
from pprint import pprint

ipdata = ipdata.IPData('test')
response = ipdata.lookup(select_field='ip')
pprint(response)
```

2020-10-30 22:51 UTC, stasdavydov commented
The `click` library has its restrictions, so I changed the CLI arguments and options the following way to fit what we need.
`cli` -- alias of `cli me`
`cli --ip 8.8.8.8` -- will lookup for 8.8.8.8
`cli --fields country_code` -- will lookup for self IP address and dump country_code only
`cli me` -- will lookup for self IP address
`cli --api-key <key> init` -- will init the API Key.
Every `cli` command can have passed `--api-key <key>` instead of using pre-initialized one.

2020-10-30 22:52 UTC, stasdavydov commented
> For `ipdata ip 1.1.1.1` is it possible to drop the `ip` sub-command so that users can just do `ipdata 1.1.1.1` to get the information for that IP?

Click library has limitations. I fixed this with `ipdata --ip 1.1.1.1`. There is no way to have multiple commands with multiple arguments with default (no-command) execution.

2020-10-31 07:32 UTC, jonathan-kosgei commented
> > For `ipdata ip 1.1.1.1` is it possible to drop the `ip` sub-command so that users can just do `ipdata 1.1.1.1` to get the information for that IP?
> 
> Click library has limitations. I fixed this with `ipdata --ip 1.1.1.1`. There is no way to have multiple commands with multiple arguments with default (no-command) execution.
> Or I should not use Click to support all of the requirements.

Is it possible to bypass click for this one command?

2020-11-02 23:48 UTC, stasdavydov commented
Batch command is implemented.

2020-11-03 09:57 UTC, jonathan-kosgei commented on ipdata/cli.py
> +
I get this error when trying to set a new api key;

```
> ipdata init test
Usage: ipdata init [OPTIONS]
Try "ipdata init --help" for help.

Error: Got unexpected extra argument (test)
```

"test" is a valid API key.

2020-11-03 18:45 UTC, stasdavydov commented
Init command is fixed.
Documentation is added.

2020-11-03 19:03 UTC, jonathan-kosgei approved these changes

2020-11-03 19:05 UTC, merged